# Generated by Django 4.2.17 on 2025-03-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceApp', '0003_device_connectivity_error_device_last_check_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_local_network',
            field=models.BooleanField(default=False, help_text='Whether this device is on the same local network as the host'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['mac_address'], name='deviceApp_d_mac_add_fb4302_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['school', 'name'], name='deviceApp_d_school__ecad9f_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['ip_address'], name='deviceApp_d_ip_addr_157d6d_idx'),
        ),
    ]
